#!/usr/bin/env node
/**
 * JSON → browser-loadable .bundle.js (works with file:// and http://)
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = join(root, "data");

for (const file of readdirSync(dataDir).filter((f) => f.endsWith(".json"))) {
  const key = basename(file, ".json");
  const json = readFileSync(join(dataDir, file), "utf8");
  JSON.parse(json); // validate before emit

  const out = [
    "/* generated by scripts/build-data.mjs — do not edit */",
    "window.TOOLCADE_BUNDLES = window.TOOLCADE_BUNDLES || {};",
    `window.TOOLCADE_BUNDLES[${JSON.stringify(key)}] = ${json};`,
    "",
  ].join("\n");

  writeFileSync(join(dataDir, `${key}.bundle.js`), out, "utf8");
  console.log(`built data/${key}.bundle.js`);
}
